### ISSUE TITLE
New tag for PR #9

### ISSUE THREAD

**Issue by sherzberg** [threatstack/threatstack-terraform#10]
Hi! We are currently implementing this terraform module and ran into the issue fixed in https://github.com/threatstack/threatstack-terraform/pull/9

Can we get a new tag/release so we can pin to an actual release with notes and not pin to a git sha? Thanks!

**Comment by olhado** [comment]
All set @sherzberg Check out 2.1.1 (https://github.com/threatstack/threatstack-terraform/releases/tag/2.1.1)

**Comment by sherzberg** [comment]
Thank you!
